name: Keep Bot Alive

on:
  schedule:
    - cron: '*/5 * * * *' # Setiap 5 menit

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
    - name: Ping Bot
      run: |
        curl https://your-replit-username.repl.co
